model:
  base_learning_rate: 4.5e-6
  target: taming.models.vqgan.VQModel
  params:
    embed_dim: 256
    n_embed: 256
    ddconfig:
      double_z: False
      z_channels: 256
      resolution: 256
      in_channels: 1
      out_ch: 1
      tanh_out: true
      ch: 32
      ch_mult: [ 1,1,2,4]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: []
      dropout: 0.0

    lossconfig:
      target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 1
        disc_start: 10000
        disc_weight: 0.8
        codebook_weight: 1.0

